default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: vagrant
  password: vagrant
  host: localhost
development:
  <<: *default
  database: ukokkei_development
test:
  <<: *default
  database: ukokkei_test