- name: Add JRE ppa
  become: yes
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Automatically select the Oracle License
  become: yes
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install JRE
  become: yes
  apt: pkg=oracle-java8-installer state=latest update-cache=yes force=yes

- name : Add repo for elasticsearch
  become: yes
  shell: wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name : Add repo for elasticsearch
  become: yes
  shell: echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list

- name : Install elasticsearch
  become: yes
  apt: name=elasticsearch state=latest update-cache=yes force=yes

- name : Set elasticsearch as servide
  become: yes
  shell: update-rc.d elasticsearch defaults 95 10